### ISSUE TITLE
Version 6.0.0 contains a Windows incompatible Soy Template Compiler breaking soy compilation (see ticket 111 on github closure template project)

### ISSUE THREAD

**Issue by gmalartre** [bolinfest/plovr#118]
Hi!

Still trying to update from 5.2.0 to 6.0.0 and experiencing issue with the soy template compiler.

I narrowed it down to this issue: [ticket 111](https://github.com/google/closure-templates/issues/111)

The exact change is the following: [137427286](https://github.com/google/closure-templates/commit/7dae5a1a2b6868da939e7643741b67db1610f190)

@valueof It would be greatly appreciated if a new version with the 111 fix could be produced.

Please do tell me if nobody as the time to do so, I might take a stab at it myself and boot up a Linux VM in order [to compile plovr with Buck on Windows](https://github.com/bolinfest/plovr/issues/117).

Thanks

**Comment by valueof** [comment]
Unfortunately, I don't have permissions to make releases on this repo. If you make a PR I'm sure @nicks or someone else will merge it.

**Comment by nicks** [comment]
good find! i think closure-templates did a release to maven to pick up the windows fixes. Now that they're a lot better at releasing to maven, i'm going to take a crack at using the maven version instead of using a git subtree.

**Comment by nicks** [comment]
ok, i've got a branch working that passes all tests on windows: https://github.com/bolinfest/plovr/tree/nicks/soymaven 

(tests on master do not pass on windows)

i would have uploaded a prebuilt jar of it, but github puts a 10MB limit on issue uploads

**Comment by gmalartre** [comment]
The branch is working as intended.

Thanks

**Comment by nicks** [comment]
fixed in 7.0
