### ISSUE TITLE
download third-party deps from maven

### ISSUE THREAD

**Issue by nicks** [bolinfest/plovr#119]
I'd like to change the Plovr build toolchain to download closure-compiler and closure-templates from Maven. The Buck support for this is getting pretty good, and it looks like they even plan on solving the transitive dependency problem (cf https://github.com/facebook/buck/issues/902)

**Comment by rgpower** [comment]
Thanks @nicks - I didn't realize that this was going to done in the very near-term.  A don't worry about the time, it was literally only 20mins or so of fooling around.

Thanks for maintaining plovr, we use it **a lot** 👍

**Comment by nicks** [comment]
good to hear!

apologies again, i didn't realize anyone would be building from head. I got pretty deep into the maven/buck integration code last night and accidentally committed the wrong test branch.

**Comment by nicks** [comment]
this is now done at head for closure-compiler and closure-templates. it would also be nice to do closure-stylesheets, but that can wait til later.
