### ISSUE TITLE
Compiler externs no longer working in 7.x.x ?

### ISSUE THREAD

**Issue by petrsloup** [bolinfest/plovr#136]
Hi,

I was previously using
```
"externs": [
    "//externs/maps/google_maps_api_v3.js"
]
```
and it was working in v6-, but does not work anymore in v7.

```
java.lang.IllegalArgumentException: resource /contrib/externs/maps/google_maps_api_v3.js relative to org.plovr.ResourceReader not found.
```

Is this a bug? Is the `//` shortcut no longer supported? Should I just download the file from closure compiler repo and have ugly duplicity in my git?

Thanks

**Comment by nicks** [comment]
I'm pretty sure we don't actually want to ship these as part of the plovr jar. It's suspect it's not a great solution for you either.

There's not really a good reason to peg the extern file to the version of the jar you're using. Note that the closure-compiler jar doesn't include them either anymore.

definitely agree with the ugly duplicity of git weirdness...tho i think that would be better solved with a tool like flow-typed that manages externs definitions.

**Comment by petrsloup** [comment]
Oh, thanks for the clarification.

In that case, it indeed does not make sense to ship all the externs as part of the plovr.jar.

I'll just have to download and handle the required externs files myself.
