### ISSUE TITLE
Dependency analysis is outdated.

### ISSUE THREAD

**Issue by KOH922** [bolinfest/plovr#162]
Dependency analysis does not correspond to `var foo = goog.require ('foo')` format.
Probably because regular expression of https://github.com/bolinfest/plovr/blob/952e2b151713aaecf570c2e24349465a056e5a9f/src/org/plovr/AbstractJsInput.java#L27-L28 is outdated.
The latest Closure-Library corresponds to `var foo = goog.require (...)` format.

The dependency analysis in Closure-Library is as follows.
https://github.com/google/closure-library/blob/b86cde2489dc50868e2769e42961318a2fd50859/closure/bin/build/source.py#L31-L32

example

config.json
```
{
    "id": "sample",
    "paths": ".",
    "inputs": "main.js"
}
```

main.js
```
var foo = goog.require('goog.ui.Component');
```

Console output
```
$ java -jar plovr.jar build config.json
main.js:1: ERROR - Closure dependency methods(goog.provide, goog.require, etc) must be called at file scope.
var foo = goog.require('goog.ui.Component');
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
```

**Comment by xvilo** [comment]
This has been fixed by now :)

**Comment by xvilo** [comment]
@KOH922 or @nicks can you close this?
