### ISSUE TITLE
closurePrimitive not recognized as JSDoc tag

### ISSUE THREAD

**Issue by xvilo** [bolinfest/plovr#174]
When running our development environment we're getting the following warnings:

```
/closure/goog/asserts/asserts.js:181: WARNING - Parse error. illegal use of unknown JSDoc tag "closurePrimitive"; ignoring it
* @closurePrimitive {asserts.truthy}
^
```

It seems this comes from Google Closure Library code, and not sure where to look for this.

![Screenshot 2019-10-07 at 15 21 26](https://user-images.githubusercontent.com/390769/66315654-7bf95180-e916-11e9-91b2-e638ba579c30.png)

**Comment by xvilo** [comment]
Also having ` WARNING - Parse error. unknown @suppress parameter: checkPrototypalTypes` from  `/closure/goog/date/date.js:17`

**Comment by xvilo** [comment]
also having

```
"/closure/goog/date/date.js:17: WARNING - Parse error. unknown @suppress parameter: checkPrototypalTypes
* @suppress {checkPrototypalTypes}
^
```

**Comment by nicks** [comment]
Hmmm...I had trouble reproducing this. I added goog.asserts and goog.date.Date to one of the examples and ran:

```
java -jar buck-out/gen/plovr.jar build testdata/modules/plovr-config.js
```

but didn't see any warnings. Is there a config option I'm missing?

**Comment by xvilo** [comment]
Seems to have solved by itself. Not sure what the issue was
