### ISSUE TITLE
Sourcemap broken

### ISSUE THREAD

**Issue by ITspirit** [bolinfest/plovr#29]
Hello,

we are using the sourcemap with plovr. 

It generates the sourcemaps (using: --create_source_map true).

But during debugging with Chrome (or Firefox) it shows the error in unpossible Codepieces.

Any ideas how to use "sourcemap" in the right way with plovr to get usefull sourcemaps?

**Comment by teppeis** [comment]
@nicks This seems to be fixed in https://github.com/bolinfest/plovr/pull/75
