### ISSUE TITLE
ConfigOption language-out is setting language-in instead

### ISSUE THREAD

**Issue by giuseppeg** [bolinfest/plovr#58]
In order to transpile ES6 code the complier `language_out` option must be set to `ES5`.
Unfortunately seems like that Plovr is using `builder.setLanguageIn` to set the `language_out` resulting in an erroneous behavior.

The snippet in question is: [ConfigOption.java#L272](https://github.com/bolinfest/plovr/blob/8555d26d19b705c85179d432354041e0e6f497d1/src/org/plovr/ConfigOption.java#L272). Is my assumption right?

```json
"experimental-compiler-options": {
    "languageIn": "ECMASCRIPT6"
}
```

**Comment by nicks** [comment]
thanks for the report!
