### ISSUE TITLE
plovr appears to ignore or not recognize all source-map related options

### ISSUE THREAD

**Issue by jmcmichael** [bolinfest/plovr#80]
I'm trying to get source maps out of plovr, but it doesn't like any of the variations of params I've tried, both as standard config and experimental options. I've tried 'create-source-map' and 'createSourceMap', as well as some other options in the source code that looked source map related, and nothing has worked.

I feel like I've exhausted all the options I can find in the docs and source - what am I missing?

This is the current config file I am working with:
``` js
{
  "id": "module-example",
  "mode": "ADVANCED",
  "language-in": "ECMASCRIPT5_STRICT",
  "inputs": [
    "../closure/library/base.js",
    "../app/js/app.js",
    "../app/states/first/first-controller.js",
    "../app/states/first/first-module.js",
    "../app/states/second/second-controller.js",
    "../app/states/second/second-module.js",
    "../app/states/third/one/one-controller.js",
    "../app/states/third/one/one-module.js",
    "../app/states/third/third-controller.js",
    "../app/states/third/third-module.js",
    "../app/states/third/two/two-controller.js",
    "../app/states/third/two/two-module.js",
    "../app/components/directives/version-directive.js",
    "../app/components/filters/check-filter.js",
    "../app/components/services/version-service.js"
  ],
  "externs": [
    "../closure/externs/angular-1.3.js",
    "../closure/externs/angular-ui-router.js"
  ],
  "debug": true,
  "level": "DEFAULT",
  "pretty-print": true,
  "output-file": "../app/js/app.min.js",
  "output-charset": "UTF-8",
  "fingerprint": true,
  "experimental-compiler-options": {
    "createSourceMap": "%outname%.map",
    "angularPass": true,
    "manageClosureDependencies": true,
    "generateExports": true,
    "removeUnusedPrototypePropertiesInExterns": false,
    "externExports": true,
    "removeUnusedPrototypeProperties": false
  },
  "global-scope-name": "__civic__"
}
```
I've also tried a string w/o the %outname% in createSourceMaps - that didn't work either.

**Comment by software-engineering** [comment]
java -jar plovr build config.js --create_source_map lala.map not in the config itself.
there is also a pull request from max v. -> https://github.com/bolinfest/plovr/pull/76

**Comment by jmcmichael** [comment]
Ok, thank you that works to save out a source map. However, it is saving out an empty .map file, and I do not appear to have the ability to name it anything besides [module-name].map. Do you know why the map file is empty? The corresponding build command issued to the compiler results in a valid .map file, so I don't think it's an issue with the source files.

**Comment by jmcmichael** [comment]
I wasn't able to figure out how to get the sourcemap out of plovr, so I'm going to switch to using a set of gulp tasks to accomplish what plovr does. I'll keep my eye on the project though, as I'd far prefer to just have one dependency on plovr than on multiple gulp plugins and custom piping.
