### ISSUE TITLE
Using ES6 'import' with plovr doesn't seem to be supported

### ISSUE THREAD

**Issue by yanhick** [bolinfest/plovr#82]
Hi,
I'm trying to update a closure project to use ES6. Using ES6 module now works with latest closure but plovr seems to "filter out" the ES6 imported modules.

From looking quickly at plovr code, It seems that it does it's own "goog.require/goog.provide" dependency resolution which would explain why ES6 modules would never be passed as input to the closure compiler.

Am I correct in this assumption? Is ES6 module a planned feature?

Thanks

**Comment by nicks** [comment]
It's something that we'll eventually support. I haven't looked into it at all or estimated the amount of work involved.

Relatedly, we're lagging behind closure-compiler by a couple months. I don't think we've pulled in the changes for ES6 modules yet.

**Comment by yanhick** [comment]
Thanks, that makes sense.
