### ISSUE TITLE
Comparison of v5.0.0 and v4.1.1 plovr jar's

### ISSUE THREAD

**Issue by adityavohra7** [bolinfest/plovr#89]
Hello!

I was upgrading a repo to the latest plovr.jar and found that git can't seem to find a difference ("git diff" yields nothing) between the v4.1.1 and v5.0.0 jars. The unix md5 command also yields the same sha for both the jars. Are these the same jars? If yes, is this expected?

**Comment by nicks** [comment]
weird...not sure what happened...i re-uploaded it

**Comment by adityavohra7** [comment]
Thanks!
