### ISSUE TITLE
Avoid recompile if input files have not changed

### ISSUE THREAD

**Issue by pcj** [bolinfest/plovr#98]
In regards to the `plovr serve` command, I've hacked `CompileRequestHandler.java` to examine input file modification dates against a cached output file and serve up the cached version if no local files have changed.  

Is this something for a PR?  

Would be interested in how others have solved this issue.

Paul

**Comment by nicks** [comment]
sure! I'd accept it.

**Comment by pcj** [comment]
OK.  I have a deadline due next week that I have to focus on but will tune it into a PR following that.

**Comment by nicks** [comment]
this has been merged
